// Generated by gencpp from file hist_kalman_mot/ObjectsInTracking.msg
// DO NOT EDIT!


#ifndef HIST_KALMAN_MOT_MESSAGE_OBJECTSINTRACKING_H
#define HIST_KALMAN_MOT_MESSAGE_OBJECTSINTRACKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <hist_kalman_mot/ObjectInTracking.h>

namespace hist_kalman_mot
{
template <class ContainerAllocator>
struct ObjectsInTracking_
{
  typedef ObjectsInTracking_<ContainerAllocator> Type;

  ObjectsInTracking_()
    : header()
    , result()  {
    }
  ObjectsInTracking_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , result(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectsInTracking_

typedef ::hist_kalman_mot::ObjectsInTracking_<std::allocator<void> > ObjectsInTracking;

typedef boost::shared_ptr< ::hist_kalman_mot::ObjectsInTracking > ObjectsInTrackingPtr;
typedef boost::shared_ptr< ::hist_kalman_mot::ObjectsInTracking const> ObjectsInTrackingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hist_kalman_mot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'hist_kalman_mot': ['/home/cc/catkin_ws/src/hist_kalman_mot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b97d14c89a53ba8269caa109e8f1f62";
  }

  static const char* value(const ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b97d14c89a53ba8ULL;
  static const uint64_t static_value2 = 0x269caa109e8f1f62ULL;
};

template<class ContainerAllocator>
struct DataType< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hist_kalman_mot/ObjectsInTracking";
  }

  static const char* value(const ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
ObjectInTracking[] result\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: hist_kalman_mot/ObjectInTracking\n\
string name\n\
string label\n\
float64 last_observed_time\n\
geometry_msgs/Point position\n\
geometry_msgs/Point velocity\n\
float64 sigma\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectsInTracking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hist_kalman_mot::ObjectsInTracking_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "result[]" << std::endl;
    for (size_t i = 0; i < v.result.size(); ++i)
    {
      s << indent << "  result[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >::stream(s, indent + "    ", v.result[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIST_KALMAN_MOT_MESSAGE_OBJECTSINTRACKING_H
