// Generated by gencpp from file hist_kalman_mot/ObjectInTracking.msg
// DO NOT EDIT!


#ifndef HIST_KALMAN_MOT_MESSAGE_OBJECTINTRACKING_H
#define HIST_KALMAN_MOT_MESSAGE_OBJECTINTRACKING_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>
#include <geometry_msgs/Point.h>

namespace hist_kalman_mot
{
template <class ContainerAllocator>
struct ObjectInTracking_
{
  typedef ObjectInTracking_<ContainerAllocator> Type;

  ObjectInTracking_()
    : name()
    , label()
    , last_observed_time(0.0)
    , position()
    , velocity()
    , sigma(0.0)  {
    }
  ObjectInTracking_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , label(_alloc)
    , last_observed_time(0.0)
    , position(_alloc)
    , velocity(_alloc)
    , sigma(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _name_type;
  _name_type name;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;

   typedef double _last_observed_time_type;
  _last_observed_time_type last_observed_time;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _velocity_type;
  _velocity_type velocity;

   typedef double _sigma_type;
  _sigma_type sigma;





  typedef boost::shared_ptr< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> const> ConstPtr;

}; // struct ObjectInTracking_

typedef ::hist_kalman_mot::ObjectInTracking_<std::allocator<void> > ObjectInTracking;

typedef boost::shared_ptr< ::hist_kalman_mot::ObjectInTracking > ObjectInTrackingPtr;
typedef boost::shared_ptr< ::hist_kalman_mot::ObjectInTracking const> ObjectInTrackingConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace hist_kalman_mot

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'hist_kalman_mot': ['/home/cc/catkin_ws/src/hist_kalman_mot/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea739d08e6075bcb32bdfb14ad1dd87f";
  }

  static const char* value(const ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea739d08e6075bcbULL;
  static const uint64_t static_value2 = 0x32bdfb14ad1dd87fULL;
};

template<class ContainerAllocator>
struct DataType< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "hist_kalman_mot/ObjectInTracking";
  }

  static const char* value(const ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n\
string label\n\
float64 last_observed_time\n\
geometry_msgs/Point position\n\
geometry_msgs/Point velocity\n\
float64 sigma\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.label);
      stream.next(m.last_observed_time);
      stream.next(m.position);
      stream.next(m.velocity);
      stream.next(m.sigma);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ObjectInTracking_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::hist_kalman_mot::ObjectInTracking_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.name);
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
    s << indent << "last_observed_time: ";
    Printer<double>::stream(s, indent + "  ", v.last_observed_time);
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.velocity);
    s << indent << "sigma: ";
    Printer<double>::stream(s, indent + "  ", v.sigma);
  }
};

} // namespace message_operations
} // namespace ros

#endif // HIST_KALMAN_MOT_MESSAGE_OBJECTINTRACKING_H
